### ISSUE TITLE
Prototype Initial Hardware Design

### ISSUE THREAD

**Issue by xKabbe** [xKabbe/star#14]
### Description

Build a small-scale version of the hardware design for preliminary testing and validation.

### Expected Actions

* [ ] Build prototype
* [ ] Test initial hardware design

### Definition Of Done

- [ ] Code implemented
- [ ] Tests implemented and passing
- [ ] Documentation implemented
- [ ] GitHub Actions are passing

**Comment by blckfox** [comment]
Closed: New milestone is going to be created for all issues.
