### ISSUE TITLE
Shopping list for hardware (Microcontrollers+Sensors)

### ISSUE THREAD

**Issue by blckfox** [xKabbe/star#44]
### Description

Create a shopping list for the various items and buy the items. 

### Expected Actions

- [x] Create shopping list for microcontroller(s)
- [x] Create shopping list for sensors
- [x] Create shopping list for misc
- [ ] Buy selected items 
- [ ] Delivery complete

### Definition Of Done

- [ ] Documentation implemented or adjusted
- [ ] GitHub Actions are passing

**Comment by xKabbe** [comment]
We should consider the following:

* Monitoring the temperature outside the box and inside the box (2x temperature sensors)
* We need to fix the thermal management problem
