### ISSUE TITLE
Assign Roles and Responsibilities

### ISSUE THREAD

**Issue by xKabbe** [xKabbe/star#6]
### Description

Clearly define and assign roles and responsibilities for each team member to ensure accountability and efficiency.

### Expected Actions

* [ ] Assign roles to team members
* [ ] Document responsibilities

### Definition Of Done

- [ ] Code implemented
- [ ] Tests implemented and passing
- [ ] Documentation implemented
- [ ] GitHub Actions are passing

**Comment by blckfox** [comment]
Will be implemented with issue #40

**Comment by xKabbe** [comment]
This was implemented by issue #40
