### ISSUE TITLE
Conduct Research on Hardware Components

### ISSUE THREAD

**Issue by xKabbe** [xKabbe/star#7]
### Description

Research various hardware components, including sensors, microcontrollers, and power options suitable for the project.
The focus should be on the electronic base components for the project. Balloons and other flight related components are discussed in another topic.

### Expected Actions

* [x] Compile a list of potential hardware components (microcontrollers)
* [x] Compile a list of potential sensors and other necessary components
* [ ] Evaluate component specifications (microcontrollers)
* [ ] Evaluate component specifications (sensors)

### Definition Of Done

- [ ] Code implemented
- [ ] Tests implemented and passing
- [ ] Documentation implemented
- [ ] GitHub Actions are passing

**Comment by blckfox** [comment]
**Possible Microcontrollers:**

- Raspberry Pi 5 
- Raspberry Pi Zero 2 W
- Arduino Nano 33 IoT
- Arduino MKR Zero
- ESP32
- BeagleBone Black

**Comment by blckfox** [comment]
Here is a current List with components where the focus lies on the ESP32-S3 module. 
The ESP32 could be changed later during a test phase if there is a better alternative.

- **Core Components**
  - ESP32 Dev Board - 1
  - MicroSD Card Module + 16 GB microSD Card - 1
  - LiPo Battery 3.7V, 2500 mAh - 1
  - Voltage Regulator and Protection Module - 1
  
- **Atmospheric Sensors**
  - BME280 (Temperature, Humidity, Pressure) - 1
  - VEML6075 (UV Sensor) - 1
  - HMC5883L (Magnetometer) - 1
  - Geiger Counter (Radiation Sensor) - 1
  - CCS811 (CO2 and Air Quality) - 1

- **Positioning and Motion Sensors**
  - NEO-6M (GPS) - 1
  - MPU6050 (Gyroscope and Accelerometer) - 1

- **Power Supply**
  - Solar Charger Controller (optional) - 1
  - Power Management Module - 1
  - Heating Pads - 2-3

- **Protective Materials**
  - Weather-Resistant Enclosure - 1
  - Insulation Material and Foam - 1
  - Silicone Sealant - 1

- **Wiring and Accessories**
  - Jumper Cables and Connectors - Set
  - Cable Ties and Velcro Straps - Set
  - Breadboard and Headers - 1

- **Software and Storage**
  - 16 GB or more microSD Card with Adapter - 1
  - Programming Cable (USB to Micro-USB) - 1

**Comment by blckfox** [comment]
Closed. For future hardware decisions and further documentation view #40
