### ISSUE TITLE
Compare Different Sensors and Microcontrollers

### ISSUE THREAD

**Issue by xKabbe** [xKabbe/star#8]
### Description

Evaluate and compare different sensors and microcontrollers based on specifications, reliability, and compatibility with the project.

### Expected Actions

* [ ] Create a comparison matrix for sensors and microcontrollers
* [ ] Select the best options

### Definition Of Done

- [ ] Code implemented
- [ ] Tests implemented and passing
- [ ] Documentation implemented
- [ ] GitHub Actions are passing

**Comment by blckfox** [comment]
Marked as done because of star #7
